### PR TITLE
Resolve merge conflicts in next

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Merge next into streamflow. This branch resolves a merge conflict between `streamflow` and `next`

### CODE REVIEW

**Comment by kyriediculous** [comment]
I think coverage is down because the refunder test is removed but the contract is still present , shall I add a commit to remove the refunder ? I mean it wasn't being used in streamflow either.

**Comment by yondonfu** [comment]
> This branch resolves a merge conflict between streamflow and next

Would an alternative have been to cherry pick the conflicting commit (I think [this one](https://github.com/livepeer/protocol/commit/d8e3523e3779a7f339b94159ad5d36ce428799cc)) into `next` right before the recent hardhat/TS/yarn related commits so that `next` could be cleanly merged into `streamflow` by sharing the same Git history prior to the recent hardhat/TS/yarn related commits?

> I think coverage is down because the refunder test is removed but the contract is still present , shall I add a commit to remove the refunder ? I mean it wasn't being used in streamflow either.

The Refunder contract is a part of the the contract system on mainnet right now ([ref](https://github.com/livepeer/wiki/blob/master/Deployed-Contract-Addresses.md)) since it was used to refund deposits from the pre-Streamflow JobsManager contract during the Streamflow upgrade. I'd be inclined to leave it for now so that the state of the `streamflow` branch can continue to reflect what is deployed on mainnet - would it be possible to add back the test for the Refunder contract?

**Comment by kyriediculous** [comment]
`next` branch is protected , you can not force push to it so cherry picking is not an option AFAIK

**Comment by yondonfu** [comment]
> `next` branch is protected , you can not force push to it so cherry picking is not an option AFAIK

What about merging your `nv/next` branch (which presumably was rebased off of `streamflow` with the conflicts resolved) into `next` via PR to line up the history on `next` with `streamflow` and then merge `next` into `streamflow` via PR?

**Comment by kyriediculous** [comment]
I changed the base to `next`, I'll look at the refunder test

**Comment by kyriediculous** [comment]
@kautukkundan will add the refunder test in a separate PR

**Review by yondonfu — DISMISSED** [review]
LGTM after resolving conflicts

**Comment by kyriediculous** [comment]
Resolved merge conflicts

**Review by yondonfu — APPROVED** [review]
LGTM!

**Pull request merged**
